// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wedgest.Data;

#nullable disable

namespace Wedgest.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20241008173554_seed data and change")]
    partial class seeddataandchange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Wedgest.Entities.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TicketId"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FromData")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ToData")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("userId")
                        .HasColumnType("int");

                    b.HasKey("TicketId");

                    b.HasIndex("userId");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("Wedgest.Entities.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("job")
                        .HasColumnType("longtext");

                    b.Property<string>("userName")
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.HasIndex("userName")
                        .IsUnique();

                    b.ToTable("user");

                    b.HasData(
                        new
                        {
                            id = 1,
                            age = 0,
                            job = "admin",
                            userName = "Mohamed"
                        },
                        new
                        {
                            id = 2,
                            age = 0,
                            job = "student",
                            userName = "Mostafa"
                        });
                });

            modelBuilder.Entity("Wedgest.Entities.Ticket", b =>
                {
                    b.HasOne("Wedgest.Entities.User", "user")
                        .WithMany("Tickets")
                        .HasForeignKey("userId");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Wedgest.Entities.User", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
